#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softdtw-deployment
  labels:
    app: softdtwforecon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softdtwforecon
  template:
    metadata:
      labels:
        app: softdtwforecon
    spec:
      containers:
      - name: softdtw
        image: raeell/softdtwforecon:latest
        ports: 
        - containerPort: 8000