#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softdtw-deployment
  labels:
    app: softdtwforecon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softdtwforecon
  template:
    metadata:
      labels:
        app: softdtwforecon
    spec:
      containers:
        - name: softdtw
          image: raeell/softdtwforecon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_DEFAULT_REGION
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SESSION_TOKEN
          - name: AWS_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_S3_ENDPOINT