#| filename: "deployment/ingress.yaml"
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeseriesforecast-bis-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - timeseriesforecast-bis.lab.sspcloud.fr
  rules:
  - host: timeseriesforecast-bis.lab.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: timeseriesforecast-bis-service
            port:
              number: 80